### ISSUE TITLE
tab-completion displayed wrong character in zsh

### ISSUE THREAD

**Issue by aliuq** [kubernetes/kubectl#1254]
**What happened**:

![image](https://user-images.githubusercontent.com/11707934/181343628-0401fae0-0b3a-41dc-b33e-6efe0cac3ea9.png)

**What you expected to happen**:

Display the right

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): `v1.23.9+k3s1`
- OS (e.g: `cat /etc/os-release`): `Linux 5.18.14-1.el7.elrepo.x86_64`
- zsh config: [.zshrc](https://github.com/aliuq/config/blob/master/bash/.zshrc)

**Comment by marckhouzam** [comment]
@aliuq this looks similar as the problem reported in https://github.com/kubernetes/kubernetes/issues/105587.  It was caused by the use of zsh 5.0.x.  Is that your case?  Zsh 5.1 or higher doesn't have the problem.  The problem has also been fixed in Cobra but has not yet been incorporated in kubectl.

Please let us know if this is the problem for you as well.

**Comment by marckhouzam** [comment]
For info, here is the fix in Cobra: https://github.com/spf13/cobra/pull/1665

**Comment by aliuq** [comment]
@marckhouzam thanks for your reply, I will try upgrade zsh now

**Comment by aliuq** [comment]
upgrade zsh version can fix it.

**Comment by brneto** [comment]
I've created the PR #112362 to fix this issue, but for those still facing this issue after installing [Oh My Zsh](https://ohmyz.sh/) with `kubectl` plugin enabled you can run command below as a patch to fix it in the meantime:
```bash
sed -i '6i\    sed -i '\''s/tab=$(printf \x27\\t\x27)/tab="$(printf \x27\\t\x27)"/'\'' "$ZSH_CACHE_DIR/completions/_kubectl"\' ~/.oh-my-zsh/plugins/kubectl/kubectl.plugin.zsh \
&& rm ~/.oh-my-zsh/cache/completions/_kubectl \
&& exec zsh
```
