### ISSUE TITLE
Faulty Kustomize version on kubectl version output

### ISSUE THREAD

**Issue by Desolar1um** [kubernetes/kubectl#1495]
**What happened**:

Non-existent Kustomize version is shown when `kubectl version` is used

```
/ # kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

**What you expected to happen**:

An existent Kustomize version to be displayed

**How to reproduce it (as minimally and precisely as possible)**:

Install kubectl v1.28.2
run `kubectl version` 

**Anything else we need to know?**:
running on alpine

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): v1.28.2, v1.25 respectively
- OS (e.g: `cat /etc/os-release`): alpine linux

**Comment by grossws** [comment]
Also when `kustomization` has `managedByLabel` (in `buildMetadata`) it writes label `app.kubernetes.io/managed-by: kustomize-(devel)` which is invalid for k8s resources.

**Comment by Chris927** [comment]
> Also when `kustomization` has `managedByLabel` (in `buildMetadata`) it writes label `app.kubernetes.io/managed-by: kustomize-(devel)` which is invalid for k8s resources.

I ran into this issue using [docker image bitnami/kubectl](https://hub.docker.com/r/bitnami/kubectl), which failed my kustomize-build with this error:

`Error from server (Invalid): error when creating "STDIN": ConfigMap "<redacted>" is invalid: metadata.labels: Invalid value: "kustomize-(devel)": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

I worked around it by downgrading to `bitnami/kubectl:1.25.15`.

**Comment by alec-w** [comment]
I've also hit this issue on 1.29.

```bash
$ kubectl version --client --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "29",
    "gitVersion": "v1.29.0",
    "gitCommit": "3f7a50f38688eb332e2a1b013678c6435d539ae6",
    "gitTreeState": "clean",
    "buildDate": "2023-12-13T08:51:44Z",
    "goVersion": "go1.21.5",
    "compiler": "gc",
    "platform": "darwin/arm64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3"
}
```

This appears to have started becoming a problem here https://github.com/kubernetes/kubectl/commit/90ca180ce06151e5bd8ff1e73756ed3d5e03f069 so affects 1.28 onwards.

The commit on kustomize this is pointing to is https://github.com/kubernetes-sigs/kustomize/commit/6ce0bf390ce3

I don't know enough about the build process, seems this was some sort of automated commit (just titled "vendor" and I can't find an associated PR, perhaps @Jefftree can shed more light on it as looks like the commit on both kustomize and kubectl came from them?).

Running a `go mod graph | grep sigs.k8s.io/kustomize/kustomize/v5` it appears there are no transitive dependencies on kustomize, perhaps this can be updated to 5.1.0 (or later? latest kustomize is 5.4.1)?

**Comment by eahangari-8x8** [comment]
Hi I also face the same issue
 app.kubernetes.io/managed-by: kustomize-(devel)
is there any solution for that? 

```
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0-eks-036c24b
```
thanks

**Comment by ardaguclu** [comment]
Please see this KEP https://github.com/kubernetes/enhancements/issues/4706 and this issue will no longer valid in the next releases.

**Comment by liggitt** [comment]
This is actually a valid module version, but could be resolved by updating to a tagged kustomize version as well

**Comment by dns2utf8-novaziun** [comment]
k3s has actually fixed it in their distribution of kubectl:
```sh
$ k3s kubectl version
Client Version: v1.30.1+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1+k3s1
```

**Comment by gppmilicia** [comment]
The issue still persists with v1.30.3:
```
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
```

**Comment by koba1t** [comment]
@gppmilicia 
Looks like that change will be released at v1.31

https://github.com/kubernetes/kubernetes/blob/099a88370d017dacf16e67306ebcdec8394fae83/CHANGELOG/CHANGELOG-1.31.md?plain=1#L1270

**Comment by kennedyoliveira** [comment]
The issue still persists with v1.31.1

```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.1+k3s1
```

**Comment by liggitt** [comment]
v5.4.2 is correct, and matches https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.4.2

**Comment by kennedyoliveira** [comment]
Why was this closed, I mentioned the issue still happens on the version 5.4.2

**Comment by liggitt** [comment]
This issue is saying the embedded kustomize version kubectl reports was not a tagged version. 

That was resolved in 1.31 when kubectl updated the embedded version of kustomize to a tagged version of v5.4.2 (instead of an untagged commit which gets reported in that v5.0.4-0.20230601165947 format), so this issue is now resolved.

**Comment by kennedyoliveira** [comment]
Oh yeah, I understand that part, what I meant is, even though it says the correct version, when you run kustomize and it has the `managedByLabel` (in `buildMetadata`) it writes label `app.kubernetes.io/managed-by: kustomize-(devel)` which is invalid for k8s resources.
Thought this issue was related to that, so the issue is still there, even though the version looks correct in the version command

**Comment by liggitt** [comment]
Ah, that should be a separate bug

**Comment by liggitt** [comment]
(and that issue should possibly be filed against the kustomize repo, I'm not sure how kustomize derives the value for that label)
